import { SignJWT, importJWK, importPKCS8 } from 'jose'
import { and, eq, ne } from 'drizzle-orm'
import { db, schema } from 'hub:db'

interface PushConfig {
  publicKey: string
  privateKey: string
  subject: string
}

type JwtSigningKey = Parameters<SignJWT['sign']>[0]

function getPushConfig(): PushConfig | null {
  const config = useRuntimeConfig()

  const publicKey = config.public.webPushPublicKey?.trim()
  const privateKey = config.webPushPrivateKey?.trim()
  const subject = config.webPushSubject?.trim()

  if (!publicKey || !privateKey || !subject)
    return null

  return {
    publicKey,
    privateKey,
    subject
  }
}

function getAudience(endpoint: string) {
  const url = new URL(endpoint)
  return `${url.protocol}//${url.host}`
}

function decodeBase64Url(base64Url: string) {
  const padded = base64Url + '='.repeat((4 - (base64Url.length % 4)) % 4)
  const base64 = padded.replace(/-/g, '+').replace(/_/g, '/')
  const binary = atob(base64)

  return Uint8Array.from(binary, char => char.charCodeAt(0))
}

function toBase64Url(bytes: Uint8Array) {
  let binary = ''

  for (const byte of bytes)
    binary += String.fromCharCode(byte)

  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '')
}

function parseVapidPublicKeyCoordinates(publicKey: string) {
  const decoded = decodeBase64Url(publicKey)

  // VAPID public key should be an uncompressed P-256 point: 0x04 || X(32) || Y(32)
  if (decoded.length !== 65 || decoded[0] !== 0x04)
    return null

  const x = toBase64Url(decoded.subarray(1, 33))
  const y = toBase64Url(decoded.subarray(33, 65))

  return { x, y }
}

async function importVapidSigningKey(config: PushConfig): Promise<JwtSigningKey> {
  // Supports PKCS8 PEM private keys (e.g. OpenSSL output).
  if (config.privateKey.includes('BEGIN PRIVATE KEY')) {
    return await importPKCS8(config.privateKey, 'ES256')
  }

  // Supports raw base64url VAPID keys commonly generated by vapidkeys.com and web-push.
  const coordinates = parseVapidPublicKeyCoordinates(config.publicKey)
  if (!coordinates) {
    throw new Error('Invalid VAPID public key format. Expected uncompressed P-256 key in base64url format.')
  }

  return await importJWK({
    kty: 'EC',
    crv: 'P-256',
    d: config.privateKey,
    x: coordinates.x,
    y: coordinates.y,
    ext: true,
    key_ops: ['sign']
  }, 'ES256')
}

async function createVapidJwt(endpoint: string, config: PushConfig) {
  const keyMaterial = await importVapidSigningKey(config)
  const nowInSeconds = Math.floor(Date.now() / 1000)

  return await new SignJWT({})
    .setProtectedHeader({ alg: 'ES256', typ: 'JWT' })
    .setAudience(getAudience(endpoint))
    .setSubject(config.subject)
    .setIssuedAt(nowInSeconds)
    .setExpirationTime(nowInSeconds + 12 * 60 * 60)
    .sign(keyMaterial)
}

async function sendSubscriptionPushWithVapidHeader(endpoint: string, config: PushConfig) {
  const jwt = await createVapidJwt(endpoint, config)

  return await fetch(endpoint, {
    method: 'POST',
    headers: {
      // RFC 8292 header format required by modern push services (notably mobile Safari/APNs).
      Authorization: `vapid t=${jwt}, k=${config.publicKey}`,
      TTL: '120',
      Urgency: 'high'
    }
  })
}

async function sendSubscriptionPushWithLegacyHeader(endpoint: string, config: PushConfig) {
  const jwt = await createVapidJwt(endpoint, config)

  return await fetch(endpoint, {
    method: 'POST',
    headers: {
      // Legacy WebPush/Crypto-Key format kept as fallback for providers expecting the old draft format.
      'Authorization': `WebPush ${jwt}`,
      'Crypto-Key': `p256ecdsa=${config.publicKey}`,
      'TTL': '120',
      'Urgency': 'high'
    }
  })
}

async function removeSubscription(endpoint: string) {
  await db
    .delete(schema.pushSubscriptions)
    .where(eq(schema.pushSubscriptions.endpoint, endpoint))
}

function isInvalidSubscriptionResponse(statusCode: number) {
  return statusCode === 404 || statusCode === 410
}

function shouldRetryWithLegacyHeader(statusCode: number) {
  return statusCode === 400 || statusCode === 401 || statusCode === 403
}

interface NotifiableIncident {
  status: string
}

export async function sendIncidentPushToOtherUsers(incident: NotifiableIncident | null | undefined, actorUserId: string) {
  if (!incident)
    return

  const config = getPushConfig()
  if (!config)
    return

  const subscriptions = await db
    .select({
      endpoint: schema.pushSubscriptions.endpoint
    })
    .from(schema.pushSubscriptions)
    .innerJoin(schema.users, eq(schema.pushSubscriptions.userId, schema.users.id))
    .where(
      and(
        ne(schema.pushSubscriptions.userId, actorUserId),
        eq(schema.users.profileComplete, 1)
      )
    )

  await Promise.all(subscriptions.map(async ({ endpoint }) => {
    try {
      let response = await sendSubscriptionPushWithVapidHeader(endpoint, config)

      if (shouldRetryWithLegacyHeader(response.status))
        response = await sendSubscriptionPushWithLegacyHeader(endpoint, config)

      if (isInvalidSubscriptionResponse(response.status))
        await removeSubscription(endpoint)
    } catch {
      // Ignore transient push delivery failures.
    }
  }))
}
